name: Build and Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3

      - id: get-version
        name: Retrieve workload version
        run: |
          VERSION=$(yq '(.version|split("-"))[0]' snap/snapcraft.yaml)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - id: snapcraft
        name: Build snap
        uses: snapcore/action-build@v1

      - id: upload
        name: Upload built snap job artifact
        uses: actions/upload-artifact@v3
        with:
          name: charmed-karapace_snap_amd64
          path: charmed-karapace_${{ steps.get-version.outputs.version }}_amd64.snap
    outputs:
      snap-file: ${{ steps.snapcraft.outputs.snap }}
      version: ${{ steps.get-version.outputs.version }}

  test:
    name: Test Snap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download snap file
        uses: actions/download-artifact@v3
        with:
          name: charmed-karapace_snap_amd64
          path: .

      - name: Install snap file
        run: |
          sudo snap install charmed-karapace_${{ needs.build.outputs.version }}_amd64.snap --dangerous

      - name: Check binaries
        run: |
          password_creation=$(charmed-karapace.mkpasswd -u test -a sha512 testpasswd)
          if echo $password_creation | grep -q '"username": "test"'; then
            echo "Password created"
          else
            exit 1
          fi
