#!/usr/bin/env bash

set -eux

export COMPONENT=karapace

export CONF="${SNAP_DATA}"/etc/$COMPONENT
export LOG="${SNAP_COMMON}"/var/log/$COMPONENT

mkdir -p $CONF
mkdir -p $LOG

cp "${SNAP}"/etc/$COMPONENT/* $CONF

chmod -R 770 "${SNAP_DATA}"/*
chmod -R 770 "${SNAP_COMMON}"/*

chown -R snap_daemon "${SNAP_DATA}"/*
chown -R snap_daemon "${SNAP_COMMON}"/*
